# This script evaluates the accuracy of different classification methods on PRODES data sample

library(sits)

# load data and fill NAs with linear interpolation
prodes.tb <- sits_getdata(system.file("extdata/time_series/prodes_226_064.json.gz", package = "sits")) %>%
    sits_linear_interp()

# view a summary of the data
sits_summary(prodes.tb)

# create list of label conversion
conv.lst <- list("Deforestation_2014" = "Clear_Cut",
                 "Deforestation_2015" = "Clear_Cut",
                 "Forest" = "Forest",
                 "Pasture" = "Pasture")

# create list for non_forest/forest classes
conv2.lst <- list("Deforestation_2014" = "Non_Forest",
                  "Deforestation_2015" = "Non_Forest",
                  "Forest" = "Forest",
                  "Pasture" = "Non_Forest")


# some ML functions computes log to perform classification. Hence, we must work on positive values.
# We transform the data time series values by shifting the data values:
positive_prodes.tb <- prodes.tb %>% sits_apply(function(band) (3 + band))


# CLUSTER Prepare
library(dtwclust)

# define a pattern generator by internal label clustering (inCLUST)
sits_intracluster_patterns <- function(data.tb = NULL, k = 3){

    result_fun1 <- function(data.tb){
        dendro.tb <- data.tb %>% dplyr::group_by(label) %>%
            dplyr::do("data" = .data, "clusters" = .data %>% (function(tb) tb %>% sits_dendrogram()))

        dendro.tb %>%
            dplyr::rowwise() %>%
            dplyr::do(sits_cluster(.data$data, .data$clusters, k) %>%
                          sits_foreach(cluster, fun = function(tb) tb %>% sits_gam())) %>%
            dplyr::mutate(label = paste0(label, ".", cluster))
    }

    result_fun2 <- function(k = k){
        dendro.tb %>%
            dplyr::rowwise() %>%
            dplyr::do(sits_cluster(.data$data, .data$clusters, k) %>%
                          sits_foreach(cluster, fun = function(tb) tb %>% sits_gam())) %>%
            dplyr::mutate(label = paste0(label, ".", cluster))
    }

    dendro.tb <- NULL
    if (!is.null(data.tb))
        dendro.tb <- data.tb %>% dplyr::group_by(label) %>%
        dplyr::do("data" = .data, "clusters" = .data %>% (function(tb) tb %>% sits_dendrogram()))

    if (is.null(dendro.tb))
        return(result_fun1)

    return(result_fun2)
}

# define a pattern generator by clustering (CLUSTER)
sits_cluster_patterns <- function(data.tb = NULL, k = 3){

    result_fun1 <- function(data.tb){
        dendro.obj <- data.tb %>% sits_dendrogram()

        sits_cluster(data.tb, dendro.obj, k) %>%
            dplyr::mutate(label = paste0("Cluster", cluster)) %>%
            sits_foreach(cluster, fun = function(tb) tb %>% sits_gam())
    }

    result_fun2 <- function(k = k){
        sits_cluster(data.tb, dendro.obj, k) %>%
            dplyr::mutate(label = paste0("Cluster", cluster)) %>%
            sits_foreach(cluster, fun = function(tb) tb %>% sits_gam())
    }

    dendro.obj <- NULL
    if (!is.null(data.tb)){
        dendro.obj <- data.tb %>% sits_dendrogram()
        return(result_fun2)
    }
    return(result_fun1)
}

#
#
#  ###################################################################

# TWDTW distances between patterns generated by GAM and time series data (TWDTW_GAM)
# This method use Machine Learning on distances between patterns and time series data.
#
# Patterns are generated by GAM only.
TWDTW_GAM_experiments.lst <- list(
    "TWDTW_GAM_SVM_radial" = list(data.tb = prodes.tb,
                                  folds = 5,
                                  pt_method = sits_gam(),
                                  dist_method = sits_TWDTW_distances(multicores = 3),
                                  tr_method = sits_svm(formula = sits_formula_linear(), kernel = "radial"),
                                  multicores = 5),
    "TWDTW_GAM_LDA" = list(data.tb = prodes.tb,
                           folds = 5,
                           pt_method = sits_gam(),
                           dist_method = sits_TWDTW_distances(multicores = 3),
                           tr_method = sits_lda(formula = sits_formula_linear()),
                           multicores = 5),
    "TWDTW_GAM_QDA" = list(data.tb = prodes.tb,
                           folds = 5,
                           pt_method = sits_gam(),
                           dist_method = sits_TWDTW_distances(multicores = 3),
                           tr_method = sits_qda(formula = sits_formula_linear()),
                           multicores = 5),
    "TWDTW_GAM_MLR" = list(data.tb = prodes.tb,
                           folds = 5,
                           pt_method = sits_gam(),
                           dist_method = sits_TWDTW_distances(multicores = 3),
                           tr_method = sits_mlr(formula = sits_formula_linear()),
                           multicores = 5),
    "TWDTW_GAM_LASSO" = list(data.tb = prodes.tb,
                             folds = 5,
                             pt_method = sits_gam(),
                             dist_method = sits_TWDTW_distances(multicores = 3),
                             tr_method = sits_glm(alpha = 1),
                             multicores = 5),
    "TWDTW_GAM_RIDGE" = list(data.tb = prodes.tb,
                             folds = 5,
                             pt_method = sits_gam(),
                             dist_method = sits_TWDTW_distances(multicores = 3),
                             tr_method = sits_glm(alpha = 0),
                             multicores = 5),
    "TWDTW_GAM_RFOR" = list(data.tb = prodes.tb,
                            folds = 5,
                            pt_method = sits_gam(),
                            dist_method = sits_TWDTW_distances(multicores = 3),
                            tr_method = sits_rfor(),
                            multicores = 5))


# TWDTW + Clustering Pattern Generator inside each lable (TWDTW_inCLUST)
# This method use Machine Learning on distances between patterns and time series data.
#
# Patterns are generated by intra class clustering followed by GAM.
TWDTW_inCLUST_experiments.lst <- list(
    "TWDTW_inCLUST_SVM_radial" = list(data.tb = prodes.tb,
                                      folds = 5,
                                      pt_method = sits_intracluster_patterns(k = 3),
                                      dist_method = sits_TWDTW_distances(multicores = 3),
                                      tr_method = sits_svm(formula = sits_formula_linear(), kernel = "radial"),
                                      multicores = 5),
    "TWDTW_inCLUST_LDA" = list(data.tb = prodes.tb,
                               folds = 5,
                               pt_method = sits_intracluster_patterns(k = 3),
                               dist_method = sits_TWDTW_distances(multicores = 3),
                               tr_method = sits_lda(formula = sits_formula_linear()),
                               multicores = 5),
    "TWDTW_inCLUST_QDA" = list(data.tb = prodes.tb,
                               folds = 5,
                               pt_method = sits_intracluster_patterns(k = 3),
                               dist_method = sits_TWDTW_distances(multicores = 3),
                               tr_method = sits_qda(formula = sits_formula_linear()),
                               multicores = 5),
    "TWDTW_inCLUST_MLR" = list(data.tb = prodes.tb,
                               folds = 5,
                               pt_method = sits_intracluster_patterns(k = 3),
                               dist_method = sits_TWDTW_distances(multicores = 3),
                               tr_method = sits_mlr(formula = sits_formula_linear()),
                               multicores = 5),
    "TWDTW_inCLUST_LASSO" = list(data.tb = prodes.tb,
                                 folds = 5,
                                 pt_method = sits_intracluster_patterns(k = 3),
                                 dist_method = sits_TWDTW_distances(multicores = 3),
                                 tr_method = sits_glm(alpha = 1),
                                 multicores = 5),
    "TWDTW_inCLUST_RIDGE" = list(data.tb = prodes.tb,
                                 folds = 5,
                                 pt_method = sits_intracluster_patterns(k = 3),
                                 dist_method = sits_TWDTW_distances(multicores = 3),
                                 tr_method = sits_glm(alpha = 0),
                                 multicores = 5),
    "TWDTW_inCLUST_RFOR" = list(data.tb = prodes.tb,
                                folds = 5,
                                pt_method = sits_intracluster_patterns(k = 3),
                                dist_method = sits_TWDTW_distances(multicores = 3),
                                tr_method = sits_rfor(),
                                multicores = 5))


# TWDTW + Clustering Pattern Generator (TWDTW_CLUSTER)
# This method use Machine Learning on distances between patterns and time series data.
#
# Patterns are generated by clustering followed by GAM.
TWDTW_CLUSTER_experiments.lst <- list(
    "TWDTW_CLUSTER_SVM_radial" = list(data.tb = prodes.tb,
                                      folds = 5,
                                      pt_method = sits_cluster_patterns(k = 12),
                                      dist_method = sits_TWDTW_distances(multicores = 3),
                                      tr_method = sits_svm(formula = sits_formula_linear(), kernel = "radial"),
                                      multicores = 5),
    "TWDTW_CLUSTER_LDA" = list(data.tb = prodes.tb,
                               folds = 5,
                               pt_method = sits_cluster_patterns(k = 12),
                               dist_method = sits_TWDTW_distances(multicores = 3),
                               tr_method = sits_lda(formula = sits_formula_linear()),
                               multicores = 5),
    "TWDTW_CLUSTER_QDA" = list(data.tb = prodes.tb,
                               folds = 5,
                               pt_method = sits_cluster_patterns(k = 12),
                               dist_method = sits_TWDTW_distances(multicores = 3),
                               tr_method = sits_qda(formula = sits_formula_linear()),
                               multicores = 5),
    "TWDTW_CLUSTER_MLR" = list(data.tb = prodes.tb,
                               folds = 5,
                               pt_method = sits_cluster_patterns(k = 12),
                               dist_method = sits_TWDTW_distances(multicores = 3),
                               tr_method = sits_mlr(formula = sits_formula_linear()),
                               multicores = 5),
    "TWDTW_CLUSTER_LASSO" = list(data.tb = prodes.tb,
                                 folds = 5,
                                 pt_method = sits_cluster_patterns(k = 12),
                                 dist_method = sits_TWDTW_distances(multicores = 3),
                                 tr_method = sits_glm(alpha = 1),
                                 multicores = 5),
    "TWDTW_CLUSTER_RIDGE" = list(data.tb = prodes.tb,
                                 folds = 5,
                                 pt_method = sits_cluster_patterns(k = 12),
                                 dist_method = sits_TWDTW_distances(multicores = 3),
                                 tr_method = sits_glm(alpha = 0),
                                 multicores = 5),
    "TWDTW_CLUSTER_RFOR" = list(data.tb = prodes.tb,
                                folds = 5,
                                pt_method = sits_cluster_patterns(k = 12),
                                dist_method = sits_TWDTW_distances(multicores = 3),
                                tr_method = sits_rfor(),
                                multicores = 5))


# TIME SERIES SPREADED (TS_SPRD)
# This method use Machine Learning directly over time series data.
# The function called to spread time series as atributes in
# SITS distance format is `sits_spread_time_series()`.
#
# No pattern needs to be created. The attributes are the time series itself.
TS_SPRD_experiments.lst <- list(
    "TS_SPRD_SVM_radial" = list(data.tb = positive_prodes.tb,
                                folds = 5,
                                pt_method = function(...) NULL,
                                dist_method = sits_spread_time_series(),
                                tr_method = sits_svm(formula = sits_formula_linear(), kernel = "radial"),
                                multicores = 5),
    "TS_SPRD_LDA" = list(data.tb = positive_prodes.tb,
                         folds = 5,
                         pt_method = function(...) NULL,
                         dist_method = sits_spread_time_series(),
                         tr_method = sits_lda(formula = sits_formula_linear()),
                         multicores = 5),
    "TS_SPRD_QDA" = list(data.tb = positive_prodes.tb,
                         folds = 5,
                         pt_method = function(...) NULL,
                         dist_method = sits_spread_time_series(),
                         tr_method = sits_qda(formula = sits_formula_linear()),
                         multicores = 5),
    "TS_SPRD_MLR" = list(data.tb = positive_prodes.tb,
                         folds = 5,
                         pt_method = function(...) NULL,
                         dist_method = sits_spread_time_series(),
                         tr_method = sits_mlr(formula = sits_formula_linear()),
                         multicores = 5),
    "TS_SPRD_LASSO" = list(data.tb = positive_prodes.tb,
                           folds = 5,
                           pt_method = function(...) NULL,
                           dist_method = sits_spread_time_series(),
                           tr_method = sits_glm(alpha = 1),
                           multicores = 5),
    "TS_SPRD_RIDGE" = list(data.tb = positive_prodes.tb,
                           folds = 5,
                           pt_method = function(...) NULL,
                           dist_method = sits_spread_time_series(),
                           tr_method = sits_glm(alpha = 0),
                           multicores = 5),
    "TS_SPRD_RFOR" = list(data.tb = positive_prodes.tb,
                          folds = 5,
                          pt_method = function(...) NULL,
                          dist_method = sits_spread_time_series(),
                          tr_method = sits_rfor(),
                          multicores = 5)
)

#
#
#  ###################################################################

# TWDTW_GAM
TWDTW_GAM_start_time <- Sys.time()
TWDTW_GAM_kfolds.lst <-
    TWDTW_GAM_experiments.lst %>% purrr::map(function(params){
        do.call(sits_kfold_validate, params)
    })
TWDTW_GAM_end_time <- Sys.time()

TWDTW_GAM_results.lst <- TWDTW_GAM_kfolds.lst %>% purrr::map2(names(TWDTW_GAM_kfolds.lst), function(kfold, kfold.name){
    conf.mx <- kfold %>% sits_accuracy(conv2.lst)
    conf.mx$name <- kfold.name
    invisible(conf.mx)
})

# TWDTW_inCLUST
TWDTW_inCLUST_start_time <- Sys.time()
TWDTW_inCLUST_kfolds.lst <-
    TWDTW_inCLUST_experiments.lst %>% purrr::map(function(params){
        do.call(sits_kfold_validate, params)
    })
TWDTW_inCLUST_end_time <- Sys.time()

TWDTW_inCLUST_results.lst <- TWDTW_inCLUST_kfolds.lst %>% purrr::map2(names(TWDTW_inCLUST_kfolds.lst), function(kfold, kfold.name){
    conf.mx <- kfold %>% sits_accuracy(conv2.lst)
    conf.mx$name <- kfold.name
    invisible(conf.mx)
})

# TWDTW_CLUSTER
TWDTW_CLUSTER_start_time <- Sys.time()
TWDTW_CLUSTER_kfolds.lst <-
    TWDTW_CLUSTER_experiments.lst %>% purrr::map(function(params){
        do.call(sits_kfold_validate, params)
    })
TWDTW_CLUSTER_end_time <- Sys.time()

TWDTW_CLUSTER_results.lst <- TWDTW_CLUSTER_kfolds.lst %>% purrr::map2(names(TWDTW_CLUSTER_kfolds.lst), function(kfold, kfold.name){
    conf.mx <- kfold %>% sits_accuracy(conv2.lst)
    conf.mx$name <- kfold.name
    invisible(conf.mx)
})

# TS_SPRD
TS_SPRD_start_time <- Sys.time()
TS_SPRD_kfolds.lst <-
    TS_SPRD_experiments.lst %>% purrr::map(function(params){
        do.call(sits_kfold_validate, params)
    })
TS_SPRD_end_time <- Sys.time()

TS_SPRD_results.lst <- TS_SPRD_kfolds.lst %>% purrr::map2(names(TS_SPRD_kfolds.lst), function(kfold, kfold.name){
    conf.mx <- kfold %>% sits_accuracy(conv2.lst)
    conf.mx$name <- kfold.name
    invisible(conf.mx)
})


working_dir = getwd()
sits_toXLSX(TWDTW_GAM_results.lst, file = paste0(working_dir, "_PRODES_TWDTW_GAM_accuracy.xlsx"))
sits_toXLSX(TWDTW_inCLUST_results.lst, file = paste0(working_dir, "_PRODES_TWDTW_inCLUST_accuracy.xlsx"))
sits_toXLSX(TWDTW_CLUSTER_results.lst, file = paste0(working_dir, "_PRODES_TWDTW_CLUSTER_accuracy.xlsx"))
sits_toXLSX(TS_SPRD_results.lst, file = paste0(working_dir, "_PRODES_TS_SPRD_accuracy.xlsx"))

#
#
#  ###################################################################


