kind: pipeline
name: default

steps:
- name: test
  image: brazildatacube/sits-r:latest
  commands:
  - R CMD build .
  - set -e; R CMD check *.tar.gz --as-cran >&1 | tee stdfile && cat stdfile | (grep -E "(WARNING)" > /dev/null) && exit 1 || exit 0

- name: coverage
  image: brazildatacube/sits-r:latest
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
  commands:
  - R -e 'library(covr); codecov(quiet = FALSE)'
  when:
    event:
    - push
