kind: pipeline
name: default

steps:
- name: test
  pull: always
  image: brazildatacube/sits:1.2.0
  commands:
  - R -e 'pacman::p_load(desc::desc_get_deps()[desc::desc_get_deps()[["type"]] != "Depends",][["package"]], install = T, update = F, character.only = T)'
  - R -e 'v<-gsub("(>) |(>=) ", "", desc::desc_get_deps()[desc::desc_get_deps()[["type"]] != "Depends" & desc::desc_get_deps()[["version"]] != "*", ][["version"]]); pacman::p_install_version(package = desc::desc_get_deps()[desc::desc_get_deps()[["type"]] != "Depends" & desc::desc_get_deps()[["version"]] != "*", ][["package"]], version = v)'
  - R CMD build .
  - set -e; R CMD check *.tar.gz --as-cran >&1 | tee stdfile && cat stdfile | (grep -E "(WARNING|ERROR)" > /dev/null) && exit 1 || exit 0
  when:
    branch:
      exclude:
      - master
    event:
    - push
    - pull_request
