# xpectr::gxs_function(fn = .config_palette_colors,
#                      args_values = list(
#                          "labels" = list(c("Araguaia", "Soy_Fallow"),
#                                          c("Dunas", "Cerrado", "Beans")),
#                          "palette" = list("default", NULL)),
#                      indentation = 4,
#                      check_nulls = TRUE)
#
#
#
#
#     ## Testing '.config_palette_colors'                                         ####
#     ## Initially generated by xpectr
#     # Testing different combinations of argument values
#
#     # Testing .config_palette_colors(labels = c("Araguai...
#     xpectr::set_test_seed(42)
#     # Assigning output
#     output_19148 <- .config_palette_colors(labels = c("Araguaia", "Soy_Fallow"), palette = "default")
#     # Testing class
#     expect_equal(
#       class(output_19148),
#       "character",
#       fixed = TRUE)
#     # Testing type
#     expect_type(
#       output_19148,
#       type = "character")
#     # Testing values
#     expect_equal(
#       output_19148,
#       c("mediumaquamarine", "orange4"),
#       fixed = TRUE)
#     # Testing names
#     expect_equal(
#       names(output_19148),
#       NULL,
#       fixed = TRUE)
#     # Testing length
#     expect_equal(
#       length(output_19148),
#       2L)
#     # Testing sum of element lengths
#     expect_equal(
#       sum(xpectr::element_lengths(output_19148)),
#       2L)
#
#     # Testing .config_palette_colors(labels = c("Dunas",...
#     # Changed from baseline: labels = c("Dunas",...
#     xpectr::set_test_seed(42)
#     # Assigning output
#     output_19370 <- .config_palette_colors(labels = c("Dunas", "Cerrado", "Beans"), palette = "default")
#     # Testing class
#     expect_equal(
#       class(output_19370),
#       "character",
#       fixed = TRUE)
#     # Testing type
#     expect_type(
#       output_19370,
#       type = "character")
#     # Testing values
#     expect_equal(
#       output_19370,
#       c("honeydew3", "yellowgreen", "lightskyblue3"),
#       fixed = TRUE)
#     # Testing names
#     expect_equal(
#       names(output_19370),
#       NULL,
#       fixed = TRUE)
#     # Testing length
#     expect_equal(
#       length(output_19370),
#       3L)
#     # Testing sum of element lengths
#     expect_equal(
#       sum(xpectr::element_lengths(output_19370)),
#       3L)
#
#     # Testing .config_palette_colors(labels = NULL, pale...
#     # Changed from baseline: labels = NULL
#     xpectr::set_test_seed(42)
#     # Testing is NULL
#     expect_true(
#       is.null(.config_palette_colors(labels = NULL, palette = "default")))
#
#     # Testing .config_palette_colors(labels = c("Araguai...
#     # Changed from baseline: palette = NULL
#     xpectr::set_test_seed(42)
#     # Testing side effects
#     # Assigning side effects
#     side_effects_18304 <- xpectr::capture_side_effects(.config_palette_colors(labels = c("Araguaia", "Soy_Fallow"), palette = NULL), reset_seed = TRUE)
#     expect_equal(
#       xpectr::strip(side_effects_18304[['error']]),
#       xpectr::strip(".config_palette_colors(labels = c: invalid colors  (.config_palette_colors(labels = c: NULL value is not allowed.)."),
#       fixed = TRUE)
#     expect_equal(
#       xpectr::strip(side_effects_18304[['error_class']]),
#       xpectr::strip(c("simpleError", "error", "condition")),
#       fixed = TRUE)
#
#     ## Finished testing '.config_palette_colors'                                ####
#     ## Testing '.config_cloud_bit_mask'                                         ####
# ## Initially generated by xpectr
# # Testing different combinations of argument values
#
# # Testing .config_cloud_bit_mask(source = "BDC", col...
# xpectr::set_test_seed(42)
# # Assigning output
# output_19584 <- .config_cloud_bit_mask(source = "BDC", collection = "CB4_64-1")
# # Testing class
# expect_equal(
#     class(output_19584),
#     "logical",
#     fixed = TRUE)
# # Testing type
# expect_type(
#     output_19584,
#     type = "logical")
# # Testing values
# expect_equal(
#     output_19584,
#     FALSE)
# # Testing names
# expect_equal(
#     names(output_19584),
#     NULL,
#     fixed = TRUE)
# # Testing length
# expect_equal(
#     length(output_19584),
#     1L)
# # Testing sum of element lengths
# expect_equal(
#     sum(xpectr::element_lengths(output_19584)),
#     1L)
#
# # Testing .config_cloud_bit_mask(source = NULL, coll...
# # Changed from baseline: source = NULL
# xpectr::set_test_seed(42)
# # Testing side effects
# # Assigning side effects
# side_effects_17891 <- xpectr::capture_side_effects(.config_cloud_bit_mask(source = NULL, collection = "CB4_64-1"), reset_seed = TRUE)
# expect_equal(
#     xpectr::strip(side_effects_17891[['error']]),
#     xpectr::strip(".config_get(key = c: key sources$collections$CB4_64-1$bands$CLOUD$bit_mask not found. Please, check the config file."),
#     fixed = TRUE)
# expect_equal(
#     xpectr::strip(side_effects_17891[['error_class']]),
#     xpectr::strip(c("simpleError", "error", "condition")),
#     fixed = TRUE)
#
# # Testing .config_cloud_bit_mask(source = "BDC", col...
# # Changed from baseline: collection = "LC8_3...
# xpectr::set_test_seed(42)
# # Assigning output
# output_15776 <- .config_cloud_bit_mask(source = "BDC", collection = "LC8_30-1")
# # Testing class
# expect_equal(
#     class(output_15776),
#     "logical",
#     fixed = TRUE)
# # Testing type
# expect_type(
#     output_15776,
#     type = "logical")
# # Testing values
# expect_equal(
#     output_15776,
#     FALSE)
# # Testing names
# expect_equal(
#     names(output_15776),
#     NULL,
#     fixed = TRUE)
# # Testing length
# expect_equal(
#     length(output_15776),
#     1L)
# # Testing sum of element lengths
# expect_equal(
#     sum(xpectr::element_lengths(output_15776)),
#     1L)
#
# # Testing .config_cloud_bit_mask(source = "BDC", col...
# # Changed from baseline: collection = NULL
# xpectr::set_test_seed(42)
# # Testing side effects
# # Assigning side effects
# side_effects_17645 <- xpectr::capture_side_effects(.config_cloud_bit_mask(source = "BDC", collection = NULL), reset_seed = TRUE)
# expect_equal(
#     xpectr::strip(side_effects_17645[['error']]),
#     xpectr::strip(".config_get(key = c: key sources$BDC$collections$bands$CLOUD$bit_mask not found. Please, check the config file."),
#     fixed = TRUE)
# expect_equal(
#     xpectr::strip(side_effects_17645[['error_class']]),
#     xpectr::strip(c("simpleError", "error", "condition")),
#     fixed = TRUE)
#
# ## Finished testing '.config_cloud_bit_mask'                                ####
