The basic data unit in the sits package is the SITS tibble, which is a way of organizing a set of time series data with associated spatial information. In R, a "tibble" differs from the traditional data frame, insofar as a tibble can contain lists embedded as column arguments. Tibbles are consistent with the "tidyverse", a collection of R package designed to work together in data manipulation. The "tidyverse" includes packages such as "ggplot2", "dplyr" and "purrr". The "SITS" package makes extensive use of the "tidyverse". 

For a better explanation of how the "SITS tibble" works, we will read a data set containing samples of land cover data for the state of Mato Grosso (MT). This state has 903,357 km\textsuperscript{2} of extension, being the third largest state of Brazil. It includes three of Brazil's biomes: Amazonia, Cerrado and Pantanal. It is the most important agricultural frontier of Brazil and is Brazil's largest producer of soybeans, corn and cotton. 

We used the MOD13Q1 product from NASA from 2001 to 2016, provided every 16 days at 250-meter spatial resolution in the Sinusoidal projection. To do the analysis, we selected the Normalized Difference Vegetation Index (NDVI) and the Enhanced Vegetation Index (EVI), and the original near infrared (NIR) and middle infrared (MIR) bands. We defined nine classes: (1) forest, (2) cerrado, (3) pasture, (4) soybean-fallow (single cropping), (5) fallow-cotton (single cropping), (6) soybean-cotton (double cropping), (7) soybean-corn (double cropping), (8) soybean-millet (double cropping), (9) soybean-sunflower (double cropping). According to the Brazilian Institute of Geography and Statistics (IBGE), crop classes (4)-(9) accounted for more than 93\% of MT agricultural land area in 2015. Crop and pasture ground data was collected by researchers Alexandre Coutinho, Julio Esquerdo and Joao Antunes from the Brazilian Agricultural Research Agency through farmer interviews in October 2009 and in October 2013. Samples for cerrado and forest classes were provided by Rodrigo Bergotti. Ground samples for soybean-fallow class were provided by Damien Arvor, based on his previous work \citep{Arvor2012}.

```{r}
# retrieve a set of samples from an RDS file
embrapa_mt.tb <- readRDS(system.file("extdata/time_series/embrapa_mt.rds", package = "sits"))
embrapa_mt.tb
```

this needs to be explained further....
