---
output: 
  pdf_document:
    citation_package: natbib
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: latex-ms.tex
title: "SITS - An R Package for Data Analysis and Machine Learning
    using Satellite Image Time Series"
author:
- name: Rolf Simoes
  affiliation: National Institute for Space Reseach, INPE, Brazil
- name: Gilberto Camara
  affiliation: National Institute for Space Reseach, INPE, Brazil
- name: Alexandre Iwata
  affiliation: Institute for Applied Economics Research (IPEA), Brazil
- name: Victor Maus
  affiliation: International Institute for Applied System Analysis (IIASA)
abstract: "Using time series derived from big Earth Observation data sets is one of the leading research trends in Land Use Science and Remote Sensing. One of the more promising uses of satellite time series is its application for classification of land use and land cover, since our growing demand for natural resources has caused major environmental impacts. The SITS package provides support on how to use statistical learning techniques with image time series. These methods include linear and quadratic discrimination analysis, support vector machines, random forests and neural networks."
date: "`r format(Sys.time(), '%B %d, %Y')`"
fontfamily: mathdesign
fontfamilyoptions: adobe-utopia
fontsize: 11pt
bibliography: references-sits.bib
biblio-style: agsm
endnote: no
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{SITS - An R Package for Data Analysis and Machine Learning
    using Satellite Image Time Series}
  %\VignetteEncoding{UTF-8}
---
```{r include = FALSE}
library(sits)
```
# Introduction 
```{r, child='./docs/sec_introd.Rmd'}
```
# Data Handling and Visualisation Basics in SITS
```{r, child='./docs/sec_data.Rmd'}
```

# Importing data into SITS
```{r, child='./docs/sec_import.Rmd'}
```

<!--
# References
\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}
\vspace*{-0.2in}
\noindent
-->
