# satellite image time series package (SITS)
# example of clustering using self-organizin maps
library(sits)

#Clustering time series samples using self-organizing maps
som_cluster <-
    sits_cluster_som(
        prodes_226_064,
        grid_xdim = 10,
        grid_ydim = 10,
        alpha = 1,
        distance = "euclidean",
        iterations = 100
    )

sits_plot_som(som_cluster)

#Remove samples that have  bad quality
new_samples.tb <- sits_som_clean_samples(som_cluster)

#Evaluate the quality of the clusters generated by SOM
cluster_overall <- sits_som_evaluate_cluster(som_cluster)
confusion_matrix <- cluster_overall$confusion_matrix
sits_plot_cluster_info(cluster_overall, "Confusion by cluster")

#Divide samples in subgroups
subgroups <- sits_som_evaluate_subgroups(som_cluster.tb)
sits_plot_subgroups(subgroups, cluster = "Soy_Corn", band = "ndvi")


