# satellite image time series package (SITS)
# example of clustering using self-organizin maps
library(sits)

#Clustering time series samples using self-organizing maps
som_cluster <-
    sits_cluster_som(
        prodes_226_064,
        grid_xdim = 10,
        grid_ydim = 10,
        rlen = 100,
        alpha = 1,
        distance = "euclidean",
        mode =  "pbatch",
        iterations = 100
    )






sits_plot_som(som_cluster.tb)

#Remove samples that have  bad quality
new_samples.tb <- sits_clean_samples_som(som_cluster.tb)

#Evaluate the quality of the clusters generated by SOM
cluster_overall <- sits_evaluate_cluster(som_cluster.tb)
confusion_matrix <- cluster_overall$confusion_matrix
sits_plot_cluster_info(cluster_overall, "Confusion by cluster")

#Divide samples in subgroups
subgroups <- sits_evaluate_som_subgroups(som_cluster.tb)
sits_plot_subgroups(subgroups, cluster = "Soy_Corn", band = "ndvi")


