# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bayes_smoother <- function(m, m_nrow, m_ncol, w, sigma, covar_sigma0) {
    .Call(`_sits_bayes_smoother`, m, m_nrow, m_ncol, w, sigma, covar_sigma0)
}

kernel_smoother <- function(m, m_nrow, m_ncol, w, normalised) {
    .Call(`_sits_kernel_smoother`, m, m_nrow, m_ncol, w, normalised)
}

bilateral_smoother <- function(m, m_nrow, m_ncol, w, tau) {
    .Call(`_sits_bilateral_smoother`, m, m_nrow, m_ncol, w, tau)
}

entropy_probs <- function(mtx, n) {
    .Call(`_sits_entropy_probs`, mtx, n)
}

least_probs <- function(mtx, n) {
    .Call(`_sits_least_probs`, mtx, n)
}

linear_interp <- function(mtx) {
    .Call(`_sits_linear_interp`, mtx)
}

linear_interp_vec <- function(vec) {
    .Call(`_sits_linear_interp_vec`, vec)
}

margin_probs <- function(mtx, n) {
    .Call(`_sits_margin_probs`, mtx, n)
}

nnls_solver <- function(x, A, iterate = 400L, tolerance = 0.000001) {
    .Call(`_sits_nnls_solver`, x, A, iterate, tolerance)
}

normalize_data <- function(data, min, max) {
    .Call(`_sits_normalize_data`, data, min, max)
}

ratio_probs <- function(mtx, n) {
    .Call(`_sits_ratio_probs`, mtx, n)
}

smooth_whit <- function(data, lambda, length) {
    .Call(`_sits_smooth_whit`, data, lambda, length)
}

smooth_whit_mtx <- function(data, lambda, length) {
    .Call(`_sits_smooth_whit_mtx`, data, lambda, length)
}

