# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bayes_smoother <- function(m, m_nrow, m_ncol, w, sigma, covar_sigma0) {
    .Call(`_sits_bayes_smoother`, m, m_nrow, m_ncol, w, sigma, covar_sigma0)
}

kernel_smoother <- function(m, m_nrow, m_ncol, w, normalised) {
    .Call(`_sits_kernel_smoother`, m, m_nrow, m_ncol, w, normalised)
}

bilateral_smoother <- function(m, m_nrow, m_ncol, w, tau) {
    .Call(`_sits_bilateral_smoother`, m, m_nrow, m_ncol, w, tau)
}

average_probs <- function(data_lst) {
    .Call(`_sits_average_probs`, data_lst)
}

weighted_probs <- function(data_lst, weights) {
    .Call(`_sits_weighted_probs`, data_lst, weights)
}

weighted_uncert_probs <- function(data_lst, unc_lst) {
    .Call(`_sits_weighted_uncert_probs`, data_lst, unc_lst)
}

entropy_probs <- function(mtx, n) {
    .Call(`_sits_entropy_probs`, mtx, n)
}

kernel_fun <- function(data, band, img_nrow, img_ncol, window_size, fun) {
    .Call(`_sits_kernel_fun`, data, band, img_nrow, img_ncol, window_size, fun)
}

least_probs <- function(mtx, n) {
    .Call(`_sits_least_probs`, mtx, n)
}

linear_interp <- function(mtx) {
    .Call(`_sits_linear_interp`, mtx)
}

linear_interp_vec <- function(vec) {
    .Call(`_sits_linear_interp_vec`, vec)
}

margin_probs <- function(mtx, n) {
    .Call(`_sits_margin_probs`, mtx, n)
}

nnls_solver <- function(x, A, iterate = 400L, tolerance = 0.000001) {
    .Call(`_sits_nnls_solver`, x, A, iterate, tolerance)
}

normalize_data <- function(data, min, max) {
    .Call(`_sits_normalize_data`, data, min, max)
}

ratio_probs <- function(mtx, n) {
    .Call(`_sits_ratio_probs`, mtx, n)
}

max_sampling <- function(data, band, img_nrow, img_ncol, window_size) {
    .Call(`_sits_max_sampling`, data, band, img_nrow, img_ncol, window_size)
}

smooth_sg <- function(data, f_res, p, n) {
    .Call(`_sits_smooth_sg`, data, f_res, p, n)
}

smooth_sg_mtx <- function(data, f_res, p, n) {
    .Call(`_sits_smooth_sg_mtx`, data, f_res, p, n)
}

smooth_whit <- function(data, lambda, length) {
    .Call(`_sits_smooth_whit`, data, lambda, length)
}

smooth_whit_mtx <- function(data, lambda, length) {
    .Call(`_sits_smooth_whit_mtx`, data, lambda, length)
}

