#' @title Export data to be used to the zoo format
#' @name sits_toZOO
#' @author Gilberto Camara, \email{gilberto.camara@@inpe.br}
#'
#' @description Converts data from a SITS tibble to an instance of a zoo series,
#'
#' @param  ts.tb    a tibble with the indexes and values of a SITS time series
#'                  the tibble should have only the time series and should not be a full tibble
#' @param  band     the name of the band to be exported (if NULL all bands are exported)
#' @return ts.zoo   a time series in zoo format
#' @examples
#'
#' # read a tibble with 400 samples of Cerrado and 346 samples of Pasture
#' cerrado2.tb <- readRDS(system.file("extdata/time_series/cerrado_2classes.rds", package = "sits"))
#' # export a time series to zoo
#' ts.zoo <- sits_toZOO (cerrado2.tb[1,]$time_series[[1]])
#'
#' @export
sits_toZOO <- function (ts.tb, band = NULL){
    if (purrr::is_null(band))
        band <-  colnames(ts.tb[-1:0])
    # transform each sits time series into a list of zoo
    return (zoo::zoo(ts.tb[,band, drop=FALSE], ts.tb$Index))
}

#' @title Saves the results of accuracy assessments as Excel files
#' @name sits_toXLSX
#' @author Gilberto Camara, \email{gilberto.camara@@inpe.br}
#
#' @description Saves confusion matrices as Excel spreadsheets. This function
#' takes the a list of confusion matrices generated by the \code{\link[sits]{sits_conf_matrix}}
#' function and save them in an Excel spreadsheet.
#'
#' @param acc.lst        A list of confusion matrices
#' @param file           The file where the XLSX data is to be saved
#'
#' @examples
#' # read a tibble with 400 samples of Cerrado and 346 samples of Pasture
#' cerrado2.tb <- readRDS(system.file("extdata/time_series/cerrado_2classes.rds", package = "sits"))
#' # perform a 2 fold validation of this sample file
#' pred_ref.tb <-  sits_kfold_validate(cerrado2.tb, folds = 2)
#' # calculate and print the confusion matrix
#' conf.mx <- sits_conf_matrix(pred_ref.tb)
#' # create a list to store the results
#' results <- list()
#' # give a name to the confusion matrix
#' conf.mx$name <- "confusion_matrix"
#' # add the confusion matrix to the results
#' results[[length(results) + 1]] <- conf.mx
#' # save the results to an XLSX file
#' sits_toXLSX(results, file = "./confusion_matrix.xlsx")
#'
#'
#' @export
sits_toXLSX <- function(acc.lst, file = NULL){

    ensurer::ensure_that (file, !purrr::is_null(.),
                          err_desc = "sits_toXLSX: please provide the file name")

    # create a workbook to save the results
    wb <- openxlsx::createWorkbook ("accuracy")

    ind <- 0

    # save all elements of the list
    purrr::map (acc.lst, function (acc.mx){
        # create a sheet name

        if (purrr::is_null(acc.mx$name)) {
            ind <<- ind + 1
            acc.mx$name <- paste0('sheet', ind)
        }
        sheet_name <- acc.mx$name

        # add a worksheet
        openxlsx::addWorksheet(wb, sheet_name)

        # use only the class names (without the "Class: " prefix)
        new_names <- unlist(strsplit(colnames(acc.mx$table), split =": "))

        # remove prefix from confusion matrix table
        colnames (acc.mx$table) <- new_names
        # write the confusion matrix table in the worksheet
        openxlsx::writeData (wb, sheet_name, acc.mx$table)

        # overall assessment (accuracy and kappa)
        acc_kappa.mx <- as.matrix(acc.mx$overall[c(1:2)])

        # save the accuracy data in the worksheet
        openxlsx::writeData (wb, sheet_name, acc_kappa.mx, rowNames = TRUE, startRow = NROW(acc.mx$table) + 3, startCol = 1)

        if (dim(acc.mx$table)[1] > 2) {
            # per class accuracy assessment
            acc_bc.mx <- t(acc.mx$byClass[,c(1:4)])
            # remove prefix from confusion matrix table
            colnames (acc_bc.mx) <- new_names
            row.names(acc_bc.mx)<- c("Sensitivity (PA)", "Specificity", "PosPredValue (UA)", "NegPredValue")
        }
        else {
            # this is the case of ony two classes
            # get the values of the User's and Producer's Accuracy for the two classes
            # the names in caret are different from the usual names in Earth observation
            acc_bc.mx <- acc.mx$byClass[grepl("(Sensitivity)|(Specificity)|(Pos Pred Value)|(Neg Pred Value)",
                                              names(acc.mx$byClass))]
            # get the names of the two classes
            nm <- row.names(acc.mx$table)
            # the first class (which is called the "positive" class by caret)
            c1 <- acc.mx$positive
            # the second class
            c2 <- nm[!(nm == acc.mx$positive)]
            # make up the values of UA and PA for the two classes
            pa1 <- paste("Prod Acc ", c1)
            pa2 <- paste("Prod Acc ", c2)
            ua1 <- paste("User Acc ", c1)
            ua2 <- paste("User Acc ", c2)
            names (acc_bc.mx) <- c(pa1, pa2, ua1, ua2)
            acc_bc.mx <- as.matrix (acc_bc.mx)
        }
        # save the perclass data in the worksheet
        openxlsx::writeData (wb, sheet_name, acc_bc.mx, rowNames = TRUE, startRow = NROW(acc.mx$table) + 8, startCol = 1)
    })

    # write the worksheets to the XLSX file
    openxlsx::saveWorkbook(wb, file = file, overwrite = TRUE)

    return (NULL)
}
