#' Find time series patterns to use using TWDTW (using the dtwSat package)
#'
#' \code{sits_init} provides the information for the dependencies of the sits package
#'
#' A sits table has the metadata and data for each time series
#' <longitude, latitude, start_date, end_date, label, coverage, time_series>
#'


.onAttach = function(lib, pkg){
     packageStartupMessage(
          sprintf("Loaded sits v%s. See ?sits for help, citation(\"sits\") for use in publication.\n",
                  utils::packageDescription("sits")$Version) )
}
# Intent:
#   This function suppresses the following notes generated by "R CMD check":"
#   - "Note: no visible binding for '<<-' assignment to 'variable'"
# Usage:
#   Add the following right in the beginning of the .R file
#   (before the Reference class is defined in the sourced .r file):
#   suppressBindingNotes(c("ConfigString"))

utils::globalVariables(c(".", "%>%", "Index", "value", "variable", "cond",
                         "rmean", "std", "stdplus", "stdminus", "cluster_id", "cross_join",
                         "longitude", "latitude", "label", "coverage",
                         "year", "start_date", "end_date", "time_series",
                         "name", "scale_factor", "missing_value"))

#' @import     magrittr
#' @import     dtwclust
#' @importFrom ensurer ensure_that ensure check check_that
#' @importFrom dplyr bind_rows contains distinct do filter cross_join inner_join left_join matches mutate num_range one_of rename rename_ rowwise select starts_with transmute
#' @importFrom readr cols  col_integer() col_double() col_date() col_character() read_csv write_lines
#' @importFrom tibble tibble as_tibble add_column add_row lst
#' @importFrom tidyr nest unnest
#' @importFrom purrr map map2 map_df is_null by_row invoke_rows
#' @importFrom ggplot2 ggplot aes geom_line labs scale_color_brewer scale_colour_hue
#' @importFrom graphics plot
#' @importFrom jsonlite fromJSON toJSON
#' @importFrom lubridate as_date dyears days period yday year ymd
#' @importFrom methods new
#' @importFrom mgcv gam predict.gam
#' @importFrom ptw whit2
#' @importFrom raster shapefile
#' @importFrom reshape2 melt
#' @importFrom signal sgolayfilt
#' @importFrom stats sd setNames
#' @importFrom tools file_ext file_path_sans_ext
#' @importFrom wtss.R WTSS timeSeries listCoverages describeCoverage
#' @importFrom zoo zoo fortify.zoo
